version: "3.8"
services:
  database:
    container_name: fulcro_getting_started_db
    image: postgres:latest
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - "15432:5432"
  app:
    container_name: fulcro_getting_started_app
    depends_on:
      - database
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        author: litewhat
    image: fulcro_getting_started:alpha
