version: "3.8"
services:
  db:
    container_name: fulcro_getting_started_db
    image: postgres:latest
    environment:
      POSTGRES_USER: fulcro_getting_started
      POSTGRES_PASSWORD: pass123
    ports:
      - "15432:5432"
