version: "3.8"
services:
  database:
    container_name: fulcro_getting_started_db
    image: postgres:latest
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - "15432:5432"
